name: Publish
on:
  release:
    types: published
env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: yarn install
    - run: yarn config set //registry.npmjs.org/:_authToken $NPM_TOKEN
    - run: yarn publish
