name: Main workflow
on: push
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: yarn install
    - run: yarn lint
    - run: yarn test
